apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
  annotations:
    recipients.argocd-notifications.argoproj.io: slack:john-test
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
      environment: development
  template:
    metadata:
      labels:
        app: guestbook-ui
        environment: development
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: guestbook-ui
        ports:
        - containerPort: 80
